### ISSUE TITLE
Cannot serve the build folder gives 404

### ISSUE THREAD

**Issue by harshalrj25** [vcaruso0923/video-chatter-2-2#4]
If a build is served locally we can create a room but the other tab which connects the room gives 404.

The node server was running at 8000 using command `node server.js`
Then `npm run build` to create a build
Then `serve build` using the serve package

Everything works fine except the fact that another user cannot join.

**Comment by vcaruso0923** [comment]
Interesting... I will have to take a look at this. I'm not familiar with the 'serve' package and have a feeling that's where the issue is. Please add any other info you can and I will try to resolve when I have time

**Comment by harshalrj25** [comment]
when the app is  deployed to heroku, I am getting the same issue hence thought of serving the build folder locally for debugging. 

You seem to have deployed this to heroku successfully...

I have deployed the app to heroku but cannot join the room [https://testwebrtcpoc.herokuapp.com/](https://testwebrtcpoc.herokuapp.com/)

**Comment by harshalrj25** [comment]
One observation, in your code, if the build folder is also deployed to Heroku, everything works fine.

And your build folder contains server.js file.
I guess something related to build folder is the issue.

**Comment by vcaruso0923** [comment]
How are you deploying to Heroku? Can you give me the steps you are following?

**Comment by harshalrj25** [comment]
@vcaruso0923 Thanks for your help..
The issue is resolved now, did some code changes and a heroku deployment using a Procfile.

Marking this issue as closed.
